# Use a imagem base do Python
FROM python:3.11-slim

# 1. Configuração base (não muda com frequência)
WORKDIR /app
ENV PYTHONPATH /app

# 2. Instalação de dependências (só muda quando requirements.txt muda)
# Copia SÓ o arquivo de dependências primeiro
COPY requirements.txt .
# Instala as dependências. Esta camada ficará em cache na maioria das vezes.
RUN pip install --no-cache-dir -r requirements.txt

# 3. Cópia do restante do projeto (muda com frequência)
# Copia todo o resto, incluindo o código da app e a pasta de dados.
# O comando "COPY . ." já inclui a pasta "data/", então a linha separada não é necessária.
COPY . .