# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
host    all             all             172.18.0.0/16           trust
host    all             all             172.18.0.0/24           trust

# Replication connections
local   replication     repmgr                                  trust
host    replication     repmgr          127.0.0.1/32            trust
host    replication     repmgr          ::1/128                 trust
host    replication     repmgr          172.18.0.0/16           trust

# Repmgr database access
local   repmgr          repmgr                                  trust
host    repmgr          repmgr          127.0.0.1/32            trust
host    repmgr          repmgr          ::1/128                 trust
host    repmgr          repmgr          172.18.0.0/16           trust
