node_id=3
node_name='postgresql-witness'
conninfo='host=postgresql-witness user=repmgr password=repmgr123 dbname=repmgr'
data_directory='/var/lib/postgresql/data'
pg_bindir=/usr/lib/postgresql/17/bin
failover=automatic
promote_command=repmgr standby promote -f /etc/repmgr.conf --log-to-file
follow_command=repmgr standby follow -f /etc/repmgr.conf --log-to-file --upstream-node-id=%n
log_file=/var/log/repmgr/repmgr.log
log_level=INFO
upstream_node_conninfo='host=postgresql-primary user=repmgr password=repmgr123 dbname=repmgr'
upstream_node_id=1 