node_id=1
node_name='repmgr-manager'
conninfo='host=postgresql-primary user=repmgr password=repmgr123 dbname=repmgr'
data_directory='/var/lib/postgresql/data'
log_file='/var/log/repmgr/repmgr.log'
log_level=INFO
